### ISSUE TITLE
The latest Docker version is failing

### ISSUE THREAD

**Issue by pismy** [Angatar/s3cmd#1]
The latest published Docker image (Nov 22th 2022 with digest `e8e760e0356aebea732e89bb59331fe8c592f56371a6bce9d4f37b1c93b63a19`) fails with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 4, in <module>
    __import__('pkg_resources').run_script('s3cmd==2.3.0.dev0', 's3cmd')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'six>=1.5' distribution was not found and is required by python-dateutil
```

**Comment by Angatar** [comment]
Hi,
Thanks for reporting this... I'll dig into this as soon as I'll have time to do it. Waiting for a fix please use the d3fk/s3cmd:stable version of the container that was pushed especially to avoid these kind of problems ;)
I'll keep you posted when a new d3fk/s3cmd:latest container version will be pushed to fix this issue.

**Comment by Angatar** [comment]
It is now fixed! 
Your next pull and run of d3fk/s3cmd:latest container should be successful.
It seems the "six" library is not declared "anymore" among dependencies and now requires to be added explicitly.

Thanks again for the bug report, it helps a lot in maintaining the latest versions working for all the community!

**Comment by pismy** [comment]
Many thanks!
